var express = require('express');
var router = express.Router();

const nameList= [
  {'Id': 1, 'Term':'Node.js', 'Description':'Node.js is an open-source, cross-platform runtime environment that allows developers to execute JavaScript code outside of a web browser. It is built on the Chrome V8 JavaScript engine and enables server-side scripting, making it possible to run JavaScript on the server, thus facilitating the development of scalable and efficient web applications.', 'reference':'S. Guerrero, MICROSERVICES IN SAP HANA XSA : a guide to rest apis using node.js. S.L.: Apress, 2020‌'}, 
  {'Id': 2, 'Term':'Deployment', 'Description':': ‘is a project management framework that breaks projects down into several dynamic phases, commonly known as sprints.', 'reference':'C. K. Riemenschneider, B. C. Hardgrave, and F. D. Davis, “Explaining software developer acceptance of methodologies: a comparison of five theoretical models,” IEEE Transactions on Software Engineering, vol. 28, no. 12, pp. 1135–1145, Dec. 2002, doi: https://doi.org/10.1109/tse.2002.1158287.'}, 
  {'Id': 3, 'Term':'Agile methodology ', 'Description':'Software testing is the process of evaluating and validating a software application to ensure that it meets the specified requirements, functions correctly, and delivers the intended results. It is a crucial phase in the software development lifecycle as it helps identify and correct software defects, errors, or discrepancies before it is deployed to end-users or customers. ', 'reference':'Sarah.L . (2022). What is Agile methodology? (A beginners guide). Available at: https://asana.com/resources/agile-methodology'}, 
  {'Id': 4, 'Term':'Jira Software ', 'Description':'Jira adapts to the way you work, not the other way around. Start simple, customize as you go.', 'reference':'atlassian (n.d.). Best software development tool used by agile teams. Available at: https://www.atlassian.com/software/jira.'}, 
  {'Id': 5, 'Term':'Data science', 'Description':'The main goal of data science is to leverage data to make data-driven decisions, solve complex problems, and gain a deeper understanding of the underlying patterns and phenomena in the data. Data scientists use their mathematics, statistics, programming, domain knowledge, and data visualization expertise to analyze data and draw meaningful conclusions.', 'reference':'F. Provost and T. Fawcett, “Data Science and its Relationship to Big Data and Data-Driven Decision Making,” Big Data, vol. 1, no. 1, pp. 51–59, Mar. 2013, doi: https://doi.org/10.1089/big.2013.1508.'}, 
  {'Id': 6, 'Term':'boilerplates', 'Description':': is a template or a set of files that provide a foundation for any website.','reference':'freecodecamp (2018). What is boilerplate and why do we use it? Necessity of coding style guide. https://www.freecodecamp.org/news/whats-boilerplate-and-why-do-we-use-it-let-s-check-out-the-coding-style-guide-ac2b6c814ee7/.'}, 
  {'Id': 8, 'Term':'Scalability ', 'Description':'is the property of a system to handle a growing amount of work. One definition for software systems specifies that this may be done by adding resources to the system. ','reference':' wikipedia (n.d.) . Available at:https://en.wikipedia.org/wiki/Scalability. Accessed on 23/07/2023.'}, 
  {'Id': 9, 'Term':' Big data ', 'Description':' Big data software solutions are designed to tackle the challenges posed by massive volumes of data, high velocity, diverse data types, and the need for real-time or near real-time data processing.', 'reference':'C. E. Otero and A. Peter, “Research Directions for Engineering Big Data Analytics Software,” IEEE Intelligent Systems, vol. 30, no. 1, pp. 13–19, Jan. 2015, doi: https://doi.org/10.1109/mis.2014.76.'}, 
  {'Id': 10, 'Term':'data visualization', 'Description':'In software development, data visualization refers to the process of displaying and presenting data in a visual format within software applications. It involves using graphical elements, such as charts, graphs, tables, maps, and other visual components, to represent complex datasets and information in a more understandable and insightful manner.', 'reference':'P. R. Holland, SAS programming and data visualization techniques : a power user’s guide. [Berkeley, CA]: Apress, 2015'}, 
  {'Id':11, 'Term':'Automation', 'Description': 'automation refers to the practice of using technology, scripts, tools, and processes to automate various tasks and workflows throughout the software development and delivery lifecycle.', 'reference':'D. Sato, Devops in Practice. Editora Casa do Código, 2014.'},
  {'Id':12, 'Term':'Agile', 'Description': 'Agile is a software development which aims to deliver valuable software to users more frequently and effectively by breaking down projects into smaller, manageable units of work called "sprints" or "iterations." ', 'reference':'Orit Hazzan and Y. Dubinsky, Agile software engineering. London: Springer, 2008.'},
{'Id':13, 'Term':'Scrum', 'Description': 'Scrum is an agile project management framework that helps teams structure and manage their work through a set of values, principles, and practice.','reference':' atlassian .(n.d). A Beginner’s Guide to Scrum . Available at: https://www.atlassian.com/agile/scrum'},
{'Id':14, 'Term':'CI/CD tools', 'Description': 'The best platform for cross-functional work, easy to organize and deliver quality work, faster.','reference':' Asana. (2023). https://asana.com.'},
{'Id':15, 'Term':'npm run', 'Description': 'The npm run command is used in Node.js and npm (Node Package Manager) to execute scripts defined in a projects package.json file. The npm run command is especially useful for automating common development tasks such as starting a development server, building production assets, running tests, and more. ', 'reference':'A. Patel, Hands-On Full-Stack Development with Swift : Develop full-stack web and native mobile applications using Swift and Vapor. Birmingham: Packt Publishing, 2018. '},
{'Id':16, 'Term':'Micro services', 'Description': 'Microservices is an architectural style in software development where a complex application is broken down into a set of smaller, loosely coupled, and independently deployable services. Each of these services represents a specific functionality or feature of the application', 'reference':'Irakli Nadareishvili, R. Mitra, M. McLarty, and M. Amundsen, Microservice Architecture. “O’Reilly Media, Inc.,” 2016.'},
{'Id':17, 'Term':'Docker', 'Description': 'Docker is a platform that enables developers to develop, ship, and run applications in containers. Containers are lightweight and portable environments that package together an applications code, runtime, libraries, and dependencies, allowing it to run consistently across different computing environments', 'reference':'Pethuru Raj, Learning Docker. 2017.'},
{'Id':18, 'Term':'Asana', 'Description': 'Open source projects make their source code available to the public, allowing anyone to view, modify, and distribute the code according to the terms of the projects license.', 'reference':'ibrary And Information Technology Association (É.-U, Open source software for libraries : an open source for libraries collaboration. Chicago: Lita, 2002.'},
{'Id':19, 'Term':'IntelliJ IDEA', 'Description': 'The IDE that makes development a more productive and enjoyable experience.','reference':' IntelliJ IDEA (2023). Available at: https://www.jetbrains.com/idea'},
{'Id':20, 'Term':'DBMS', 'Description': 'DBMS stands for "Database Management System." Its a software system designed to manage, store, retrieve, and manipulate data in a structured and organized way. A DBMS provides an interface for users and applications to interact with databases, ensuring data integrity, security, and efficient data management.', 'reference':'B. L. Larson, SQL solutions for IBM DBMS. New York: Vnr Van Nostrand Reinhold, 1991.'}
  
  ];

 
/* GET home page. */
router.get('/', function(req, res, next) {
  res.render('index', { title: 'Sit722- - Software Deployment And Operation', subheading: 'Below is the table containing collection of DevOps terms and their descriptions with references' });
});

module.exports = router;
